<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.wlpiaoyi</groupId>
        <artifactId>framework</artifactId>
        <version>1.0.2-JDK21</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <groupId>org.wlpiaoyi.framework.lab</groupId>
    <artifactId>iotda</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <iot.device.version>1.2.2</iot.device.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.wlpiaoyi.framework</groupId>
            <artifactId>utils</artifactId>
        </dependency>
        <dependency>
            <groupId>com.huaweicloud</groupId>
            <artifactId>iot-device-sdk-java</artifactId>
            <version>${iot.device.version}</version>
        </dependency>
    </dependencies>

</project>